In [1]:
import numpy

In [3]:
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [5]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
import cv2

In [11]:
im_g = cv2.imread('smallgrey.png', 0) # 0: greyscale 1: RGB/BGR (bands)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [12]:
im_g = cv2.imread('smallgrey.png', 1) # 0: greyscale 1: RGB/BGR (bands)
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [13]:
cv2.imwrite('newsmallgrey.png',im_g)

True

In [17]:
im_g = cv2.imread('smallgrey.png', 0)
im_g[0:2] # slice first two rows

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [18]:
im_g[0:2,2:4] # slicing portions of the image matrix/array

array([[104, 121],
       [255, 255]], dtype=uint8)

In [20]:
im_g.shape

(3, 5)

In [21]:
for i in im_g: # iterate through rows of 2-d numpy array using for
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [22]:
for i in im_g.T: # iterate through columns of (transposed) 2-d numpy array using 'for'
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [23]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [31]:
ims = numpy.hstack((im_g,numpy.array([[1,2,3],[1,2,3],[1,2,3]])))  # horizontal stack using tuple
ims

array([[187, 158, 104, 121, 143,   1,   2,   3],
       [198, 125, 255, 255, 147,   1,   2,   3],
       [209, 134, 255,  97, 182,   1,   2,   3]])

In [37]:
ims = numpy.vstack((im_g,numpy.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])))  # vertical stack using tuple
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [  1,   2,   3,   4,   5],
       [  1,   2,   3,   4,   5],
       [  1,   2,   3,   4,   5]])

In [40]:
lst = numpy.hsplit(ims,5) # horizontal split - beware splitting non-evenly split columns
lst

[array([[187],
        [198],
        [209],
        [  1],
        [  1],
        [  1]]), array([[158],
        [125],
        [134],
        [  2],
        [  2],
        [  2]]), array([[104],
        [255],
        [255],
        [  3],
        [  3],
        [  3]]), array([[121],
        [255],
        [ 97],
        [  4],
        [  4],
        [  4]]), array([[143],
        [147],
        [182],
        [  5],
        [  5],
        [  5]])]

In [43]:
lst2 = numpy.vsplit(ims,3) # vertical split - beware splitting non-evenly split columns
lst2

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]]), array([[209, 134, 255,  97, 182],
        [  1,   2,   3,   4,   5]]), array([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])]